window.receiveLectureContent({
  "id": "cv46",
  "title": "Lecture #46: Physiology - Lung Mechanics: Pressures Acting on the System",
  "lecturer": "Vishwa Rajagopalan, Ph.D., FAHA, FCVS",
  "pdf": "content/CV46_HighYield_Render.pdf",
  "content": `
# Lecture #46: Physiology - Lung Mechanics: Pressures Acting on the System

**Lecturer:** Vishwa Rajagopalan, Ph.D., FAHA, FCVS
**Session:** Lecture #46

## Ventilation: Air Moved vs. Air Exchanged (Slides 3-7)

Ventilation is the result of mechanical forces generated by the chest wall and the lungs (Slide 5). The lung is an elastic structure that collapses like a balloon and would expel its air through the trachea if nothing held it inflated; it has no attachment to the chest wall except where it is suspended at the hilum from the mediastinum, so it effectively floats in the thoracic cavity within a thin film of pleural fluid. Because nothing tethers it, **pressure alone determines lung volume** - which is why the rest of the lecture is about pressures. First, though, the air you move has to be separated from the air that actually reaches gas exchange.

- **Volumes and capacities (Slide 4), recalled from [[CV45]]:** tidal volume (normal breathing), inspiratory reserve volume (deep inspiration), expiratory reserve volume (expiration beyond normal), and residual volume (cannot be exhaled voluntarily). Combining them gives inspiratory capacity, vital capacity (or forced vital capacity), functional residual capacity, and total lung capacity.
- **Pulmonary ventilation = minute ventilation = minute volume:** gross ventilation per minute, the round trip of air in and out over one minute (Slide 6).
- **Alveolar ventilation:** only the fresh air reaching gas-exchange areas, so dead space must be subtracted first.

| Quantity | Formula | This lecture's numbers (Slides 6-7) |
| --- | --- | --- |
| Pulmonary (minute) ventilation | VT x RR | 500 mL x 15/min = 7.5 L/min |
| Alveolar ventilation | (VT - VD) x RR | (500 - 150) x 15 = 5250 mL/min (~5.2-5.3 L/min) |
| Tidal volume / dead space | - | 500 mL / ~150 mL |
| Respiratory rate | - | 12-18/min in adults (15 used here) |
| Alveolar gas volume | - | ~3000 mL |

- **Cardiac parallel [Lecturer Emphasis]:** minute ventilation is to the lung what cardiac output (SV x HR) is to the heart - same structure, gas instead of liquid.
- **Dead space, healthy vs diseased:** anatomic and physiologic dead space are nearly equal in a normal lung because **all alveoli are functional**. In some pathologies physiologic dead space rises to as much as **10 times** the anatomic value - **1 to 2 liters** - so alveolar ventilation falls even when minute ventilation looks normal.
- **The igloo analogy (Slide 10) [Lecturer Emphasis]:** a doorless igloo with a chimney pump and an internal fire; pump speed models ventilation rate, fire size models perfusion. The retained point: the heart and the gut each have a separate inflow and outflow, but the lung has **one pipe for both directions**, so incoming and outgoing air share the trachea.

## Changing Thoracic Volume: The Muscles (Slides 9-16)

The lung cannot expand itself, so every pressure change in this lecture begins as a change in the volume of the rib cage and abdomen (Slide 9). There are only two geometric maneuvers: the diaphragm moves **down or up** to lengthen or shorten the chest cavity, and the ribs **elevate or depress** to change the anterior-posterior diameter. Everything downstream - pleural pressure, alveolar pressure, airflow - is a consequence of those two.

- **The diaphragm, arguably the most important muscle of inspiration (Slide 10) [Lecturer Emphasis]:**
  - **Inspiration:** it contracts and **flattens**; ribs move **up and out**; vertical diameter increases and AP thickness increases by **at least 20%**.
  - **Expiration:** it relaxes and **domes upward**; ribs move **down and in**.
  - Abdominal contents are pushed **downward** while ribs lift **upward and outward** - thorax and abdomen cooperate on every single breath.
- **Principal muscles of inspiration (Slide 11):** external intercostals (elevate the ribs), the **interchondral part of the internal intercostals** (also elevate the ribs - not the whole internal intercostal layer), and the diaphragm, which descends, increases the longitudinal dimension of the chest, and elevates the lower ribs.
- **Accessory muscles of inspiration:** sternocleidomastoid and scalenes, recruited only for exerted inspiration.
- **Muscles of expiration:** normally none. When expiration becomes active: internal intercostals plus the abdominal wall - rectus abdominis, external oblique, internal oblique, transversus abdominis.
- **Rib motion (Slide 12):** external intercostals produce **upward and forward** movement of the rib cage, described by two analogies the lecturer explicitly asks you to remember.
- **Mechanical advantage map (Slide 16):** the most **rostral and dorsal** external intercostals plus the **parasternal** internal intercostals have an **inspiratory** mechanical advantage; the **caudal** internal intercostals, the **caudal-ventral** external intercostals, and the **transversus thoracis (triangularis sterni)** have an **expiratory** mechanical advantage.

:::mnemonic
**Two Rib Motions**
**BUCKET goes side, PUMP goes front**

- **Bucket handle:** rib shafts swing laterally like a bucket handle - **lateral (transverse)** increase in volume.
- **Pump handle:** the sternum lifts like an old water-pump handle - **anterior (A-P)** increase in volume.
:::

:::diagram cv46-rib-motions:::

- **Active vs passive (Slide 13):** in resting breathing inspiration is **active** and expiration is **passive (or mainly passive)**. In vigorous breathing **both are active** - inspiration uses diaphragm plus accessory muscles, expiration uses accessory muscles of expiration. Vigorous breathing is not only pathologic; extreme altitude does it too. The lecturer describes climbing to **5630 m (about 18,500 ft)** in the Himalayas, where even a casual step demanded hard, difficult breathing [Lecturer Emphasis].
- **Recruitment thresholds by minute volume in a healthy adult (Slides 14-15):**

| Muscle group | Minute volume at which it begins to contribute |
| --- | --- |
| Diaphragm, external intercostals | resting breathing |
| Internal intercostals | resting breathing |
| Abdominal muscles | ~40 L/min |
| Sternocleidomastoid, serratus anterior | ~50 L/min |
| Spinal erectors, trapezius, posterior neck | ~100 L/min |

- **Disease shifts the whole table left [Lecturer Emphasis]:** when airways are partially obstructed or lung movement is restricted, these same muscles become active at **much lower** minute volumes.
- **Elastic recoil does resting expiration (Slide 16):** the diaphragm is simply relaxed. In exercise or in asthma the **abdominals contract** while the diaphragm relaxes, adding to the recoil of lung, chest wall, and abdominal structures.

:::correlate
Conditions That Impair Diaphragm Function

- **Pathophysiology:** paradoxical movement, ascites, pregnancy, and obesity all oppose or splint diaphragmatic descent (Slide 17). The resting balance point of the lung-chest wall system shifts and **functional residual capacity decreases**.
- **Diagnosis:** a fall in FRC is the shared signature. Recall **FRC = RV + ERV**.
- **Lecturer's Point:** the diaphragm is the crucial muscle of quiet, peaceful breathing, so anything limiting its excursion is a breathing problem even when the lung tissue itself is entirely normal.
:::

## The Three Pressures and Why Two of Them Are Negative (Slides 18-22)

Three pressures do all the work: **intrapleural, alveolar, and transpulmonary** (Slide 18). They are expressed in **cm H2O** rather than mmHg because early investigators relied on water manometers, which were more sensitive than mercury manometers, and because mercury is the more hazardous fluid. Every value is **relative to atmospheric pressure, which is defined as zero**. Understanding why the pleural value sits below zero explains both normal breathing and the two pleural emergencies that follow.

- **The intrapleural gradient:** pleural pressure is **more negative at the apex than at the base**, though it stays negative at the base, because of **gravity and posture**. The lecture works with **-5 cm H2O** as the average. A headstand changes these dynamics; in microgravity the intrapleural gradient **vanishes entirely**.
- **The intrapleural space (Slide 19):** visceral and parietal pleura separated by pleural fluid across a space only **5 to 35 microns** thick - a relative vacuum at FRC.
- **Two sources of the negative pressure (Slide 20):**
  1. The **lymphatic system continuously drains pleural fluid**, generating suction.
  2. The **elasticity of the lung and chest wall**: after a quiet expiration the lung's inward recoil and the chest wall's outward recoil are equal and opposite (Slides 21-22). It is a tug-of-war between two teams pulling one rope, and the negative pleural pressure is the rope holding still.

:::diagram cv46-pleural-balance:::

:::correlate
Pneumothorax

- **Pathophysiology:** air enters the pleural space through rupture or puncture of the lung or chest wall. Pleural pressure becomes **less negative**, **transpulmonary pressure falls toward zero**, and unopposed elastic recoil collapses the lung (Slide 21).
- **Presentation:** the lecturer's settings are **stab wounds and trauma**, and **after cardiothoracic surgery**, where air is found in the pleural cavity.
- **Diagnosis:** imaging showing a collapsed lung on the affected side.
- **Complications:** in mild pneumothorax pleural pressure only rises toward **0 (atmospheric)**; in **severe tension pneumothorax it becomes strongly positive**, which is the dangerous form.
- **Lecturer's Point:** the **mediastinal membrane prevents the other lung from collapsing**, which is why a unilateral pneumothorax leaves one functioning lung.
:::

:::correlate
Pleural Effusion

- **Pathophysiology:** fluid rather than air accumulates in the pleural space. Only an optimal thin film belongs there; excess fluid displaces air from the dependent lung.
- **Diagnosis:** chest x-ray showing dramatic fluid collection at the lung base, with **hardly any visible air** in the affected lower zone (Slide 21).
- **Treatment:** **thoracentesis**, also called pleural tapping - a needle is inserted carefully into the pleural cavity and fluid is drained over a good period of time, then the needle is removed carefully **so that air does not get trapped inside** (which would trade an effusion for a pneumothorax).
- **Lecturer's Point:** both pleural correlates make the same physiologic point - the pleural space tolerates neither extra air nor extra fluid, because either one abolishes the negative pressure that holds the lung open.
:::

## Alveolar Pressure Through One Breath (Slides 23-31)

Muscle work reaches the alveolus as a **volume** change, and Boyle's law converts it into a **pressure** change: at constant temperature the pressure and volume of a gas are inversely proportional (P1V1 = P2V2). Expand the thorax and alveolar pressure falls below atmospheric; compress it and alveolar pressure rises above atmospheric. Air then flows down the resulting gradient until the gradient is zero. The chain always runs muscles to pleural pressure to lung volume to alveolar pressure to airflow, never the other way.

- **At rest, at FRC (Slides 23-24):** alveolar pressure **0**, atmospheric **0**, intrapleural **-5**. Respiratory muscles are at rest, lung and chest wall recoil are **equal but opposite**, pressure along the tracheobronchial tree is atmospheric, and there is **no airflow** because the system is in equilibrium.
- **Inspiration, in five steps (Slides 26-28):**
  1. Inspiratory muscles contract and the thoracic cavity expands.
  2. The chest wall pulls on the pleural space: intrapleural pressure goes **-5 to -8**.
  3. The more negative pleural pressure pulls on the lungs and expands them.
  4. Lung volume rises, so alveolar pressure drops sub-atmospheric: **0 to -1**.
  5. Air flows in down the gradient until the gradient is again zero.
- **Expiration (Slides 29-31):**
  1. Inspiratory muscles relax and thoracic volume declines.
  2. Intrapleural pressure returns **-8 to -5**.
  3. The lungs decrease in size and deflation compresses alveolar gas.
  4. Alveolar pressure rises above atmospheric: **0 to +1**, and this positive value is what expels the CO2-rich air.
  5. Outflowing air returns alveolar pressure toward **0**; at zero, airflow stops.
  - Deflation continues until the **lung recoil force decreases to again equal the intrapleural pressure** - and that point *is* FRC, the baseline from which the next breath begins (Slide 31).

| Instant | Alveolar (PA) | Intrapleural (Ppl) | Transpulmonary (PA - Ppl) | Airflow |
| --- | --- | --- | --- | --- |
| Rest / FRC | 0 | -5 | +5 | none |
| End of inspiration | -1 | -8 | +7 (largest) | in |
| Mid-expiration | +1 | -5 | +6 | out |

:::diagram cv46-pressure-cycle:::

:::highyield
Own the numbers: intrapleural runs **-5 to -8 to -5** across one breath; alveolar runs **0 to -1 to 0 to +1 to 0**. Atmospheric pressure is always the zero reference. **Alveolar pressure is the only one of the two that ever becomes positive**, and that positive value is what pushes air out.
:::

## Transpulmonary Pressure: The Gap Between the Curves (Slides 32-34)

Transpulmonary pressure is not a fourth event in the cycle - it is the arithmetic difference between the two curves already tracked. Both transpulmonary pressure and transairway pressure are defined as **pressure inside minus pressure outside**, and in both cases the outside pressure is the **pleural** pressure (Slide 32). What transpulmonary pressure measures is the **elastic recoil pressure**: the elastic forces in the lungs that tend to collapse them at each instant of respiration.

- **PL = PA - Ppl** (Slides 32, 34). The pressures named on Slide 32 are airway (Paw), alveolar (PA), pleural (Ppl), transpulmonary (PL), and transairway (Pta).
- **The combined chart (Slide 33) [Lecturer Emphasis - practise drawing this by hand]:** tidal volume rises 0 to 500 mL and returns to 0; alveolar pressure dips negative during inspiration and swings positive during expiration; pleural pressure falls from -5 to -8 and curves back. Airflow traces the **same shape** as the alveolar pressure curve even though its values differ.
  - The vertical gap between the alveolar and pleural traces at any instant **is** the transpulmonary pressure, and it is **deepest at end-inspiration**, when the expanded lung recoils hardest. (Reading the printed curve aloud the lecturer briefly said -2.5; the alveolar value he repeats and quizzes on is **-1**.)
- **System summary (Slide 34):** the **outward** elastic recoil of the chest wall (pleural pressure minus pressure at the chest surface) is opposed by the **inward** elastic recoil of the lungs (alveolar minus intrapleural pressure). During ventilation, air flows **only because of pressure gradients**.
- **Quick quiz (Slide 36):** as inspiration proceeds, pleural pressure reaches **-8 cm H2O**. Why: as the lung expands, its recoil pressure increases, so pleural pressure must fall further to oppose the lung's rising tendency to collapse.

## Obstructive vs Restrictive Disease (Slide 35)

The lecture closes by turning the pressure framework into a diagnostic lens. Each pattern is a failure to generate one **sign** of alveolar pressure. Obstructive disease cannot build enough **positive** alveolar pressure to drive air out, so air is trapped behind partly obstructed airways. Restrictive disease cannot build enough **negative** alveolar pressure to draw air in, so a stiff lung never fills.

| Feature | Obstructive (asthma, chronic bronchitis) | Restrictive (pulmonary fibrosis) |
| --- | --- | --- |
| Pressure failure | cannot develop **+** alveolar pressure | cannot develop **-** alveolar pressure |
| Core problem | air left behind after expiration | too little air taken in on inspiration |
| Residual volume | increased | decreased |
| FRC | increased | decreased |
| TLC | - | decreased (lung will not stretch) |

:::highyield
One sign flips the diagnosis. **Loss of positive alveolar pressure = obstructive** (air trapping, so RV and FRC rise). **Loss of negative alveolar pressure = restrictive** (poor filling, so FRC and TLC fall). In restrictive disease essentially every volume falls together, which is itself the memory device.
:::

:::correlate
Obstructive Lung Disease (Asthma, Chronic Bronchitis)

- **Pathophysiology:** airways are partially obstructed, so the lung loses the ability to develop the **positive** alveolar pressure needed to drive air out; air is retained after expiration.
- **Diagnosis:** **increased residual volume and increased FRC** - both of which represent air left in the lung after expiration (Slide 35).
- **Treatment:** not covered here beyond mechanics; the lecture notes that in asthma expiration becomes an **active** process, with the abdominals contracting exactly as in exercise (Slide 16).
- **Lecturer's Point:** obstruction also recruits accessory muscles at far lower minute volumes than the healthy thresholds listed above.
:::

:::correlate
Restrictive Lung Disease (Pulmonary Fibrosis)

- **Pathophysiology:** the lung is stiff and hard to expand, so what is lost is the ability to develop a sufficiently **negative** alveolar pressure; less air is taken in with each inspiration.
- **Diagnosis:** **decreased FRC** (less air taken in with inspiration) and **decreased TLC** (the lungs are hard to expand and cannot stretch on inspiration). RV, ERV and tidal volume fall as well.
- **Lecturer's Point:** learn the two side by side - obstructive raises the leftover-air volumes, restrictive lowers nearly everything.
:::
`,
  "flashcards": [
    { "front": "What is the formula for pulmonary (minute) ventilation, and what is its cardiac analogue?", "back": "Minute ventilation = tidal volume x respiratory rate (VT x RR). The analogue is cardiac output = stroke volume x heart rate.", "tag": "Concept" },
    { "front": "Calculate alveolar ventilation from this lecture's numbers.", "back": "(VT - VD) x RR = (500 - 150) mL x 15/min = 5250 mL/min, about 5.2-5.3 L/min. Minute ventilation with the same numbers is 7.5 L/min.", "tag": "Concept" },
    { "front": "How do anatomic and physiologic dead space compare in health and in disease?", "back": "Nearly equal in a healthy lung because all alveoli are functional. In some pathologies physiologic dead space can reach 10 times the anatomic value, up to 1-2 L.", "tag": "Clinical" },
    { "front": "What are the two geometric ways the lungs are expanded and contracted?", "back": "Downward/upward movement of the diaphragm to lengthen or shorten the chest cavity, and elevation/depression of the ribs to change the anterior-posterior diameter.", "tag": "Concept" },
    { "front": "Which portion of the internal intercostals assists inspiration?", "back": "The interchondral (parasternal) part, which elevates the ribs - not the whole internal intercostal layer. The rest of the internal intercostals act in expiration.", "tag": "Glossary" },
    { "front": "Distinguish bucket handle from pump handle rib motion.", "back": "Bucket handle: rib shafts swing laterally, giving a lateral (transverse) increase in thoracic volume. Pump handle: the sternum lifts anteriorly, giving an anterior-posterior increase. AP thickness rises by at least 20%.", "tag": "Concept" },
    { "front": "At what minute volumes do accessory muscles begin to contribute in a healthy adult?", "back": "Abdominals ~40 L/min; sternocleidomastoid and serratus anterior ~50 L/min; spinal erectors, trapezius and posterior neck muscles ~100 L/min. Diaphragm and intercostals work at rest. Obstruction or restriction recruits all of them at much lower minute volumes.", "tag": "Clinical" },
    { "front": "Which four conditions were listed as impairing diaphragm function, and what happens to FRC?", "back": "Paradoxical movement, ascites, pregnancy and obesity. Functional residual capacity decreases (FRC = RV + ERV).", "tag": "Clinical" },
    { "front": "Name the two mechanisms that keep intrapleural pressure negative.", "back": "1) The lymphatic system continuously drains pleural fluid, generating negative pressure. 2) The elasticity of the lungs and chest wall - inward lung recoil balanced against outward chest wall recoil.", "tag": "Concept" },
    { "front": "Why is pleural pressure more negative at the apex than at the base, and what abolishes the gradient?", "back": "Gravity and posture. A headstand alters the dynamics, and in microgravity the intrapleural gradient vanishes. The lecture uses -5 cm H2O as the average value.", "tag": "Concept" },
    { "front": "Trace alveolar and intrapleural pressure across one quiet breath.", "back": "Intrapleural: -5 to -8 (end inspiration) to -5. Alveolar: 0 to -1 (inspiration) to 0 to +1 (expiration) to 0. Atmospheric pressure is always the zero reference.", "tag": "Concept" },
    { "front": "Define transpulmonary pressure and state what it measures.", "back": "PL = alveolar pressure - pleural pressure (inside minus outside, with pleural pressure as the outside term). It is the elastic recoil pressure: the elastic forces tending to collapse the lungs at each instant of respiration.", "tag": "Glossary" },
    { "front": "What happens to pleural and transpulmonary pressure in pneumothorax?", "back": "Air in the pleural space makes pleural pressure less negative; transpulmonary pressure falls to zero and elastic recoil collapses the lung. Mild pneumothorax approaches 0 (atmospheric); severe tension pneumothorax becomes strongly positive. The mediastinal membrane keeps the other lung inflated.", "tag": "Clinical" },
    { "front": "What is thoracentesis, and what is the key technical caution?", "back": "Pleural tapping - a needle placed carefully into the pleural cavity to drain a large fluid collection over time. Withdraw carefully so that air is not trapped inside, which would convert the effusion into a pneumothorax.", "tag": "Clinical" },
    { "front": "Contrast the pressure failure in obstructive vs restrictive lung disease.", "back": "Obstructive (asthma, chronic bronchitis): loss of the ability to develop POSITIVE alveolar pressure, so RV and FRC increase. Restrictive (pulmonary fibrosis): loss of the ability to develop NEGATIVE alveolar pressure, so FRC and TLC decrease.", "tag": "Clinical" },
    { "front": "As inspiration proceeds, how far does pleural pressure fall, and why?", "back": "To -8 cm H2O. As the lung expands, its recoil pressure increases, so pleural pressure must fall further to oppose the lung's rising tendency to collapse.", "tag": "Concept" }
  ],
  "questions": [
    {
      "question": "A healthy adult breathes 15 times per minute with a tidal volume of 500 mL and an anatomic dead space of 150 mL. Which value represents the fresh air reaching the gas-exchange areas of the lungs each minute?",
      "options": ["A. 7500 mL/min, since every milliliter of each inspired breath eventually reaches an alveolus", "B. 2250 mL/min, the volume that remains within the conducting airways at end-inspiration", "C. 5250 mL/min, or roughly 5.2 to 5.3 L/min", "D. 9750 mL/min, obtained by adding dead space to tidal volume before multiplying by rate", "E. 3000 mL/min, the volume of alveolar gas present in the lungs at the end of a quiet breath"],
      "answer": "C",
      "rationale": "Alveolar ventilation = (VT - VD) x RR = (500 - 150) x 15 = 5250 mL/min. Minute (pulmonary) ventilation with the same numbers is 500 x 15 = 7500 mL/min, which counts the dead space air that never reaches gas exchange.",
      "hidden": true
    },
    {
      "question": "During quiet inspiration in a healthy adult, which combination of events occurs?",
      "options": ["A. The diaphragm domes upward as it relaxes while the ribs are simultaneously drawn downward and inward", "B. The diaphragm contracts and flattens while the ribs move upward and outward", "C. The diaphragm contracts and flattens while the abdominal wall muscles contract to raise abdominal pressure", "D. The diaphragm relaxes while the external intercostals depress the ribs to lengthen the thoracic cavity", "E. The diaphragm remains isometric while the sternocleidomastoid and scalenes generate the entire volume change"],
      "answer": "B",
      "rationale": "Diaphragmatic contraction flattens the dome and is crucial for normal inspiration; the ribs move up and out, increasing both vertical and anterior-posterior dimensions (AP thickness by at least 20%). Relaxation with doming and ribs moving down and in is expiration.",
      "hidden": true
    },
    {
      "question": "A patient with lung disease has a physiologic dead space of approximately 1.5 L while the anatomic dead space remains near 150 mL. Which statement best explains this discrepancy?",
      "options": ["A. The conducting airways have physically enlarged to roughly ten times their normal anatomic volume", "B. Tidal volume has increased so much that dead space measurement is artificially inflated by the calculation", "C. Residual volume has been added to the anatomic dead space in this measurement technique", "D. The lymphatic drainage of pleural fluid has failed, adding fluid volume to the measured dead space", "E. Some alveoli are no longer functional, so their volume behaves as dead space"],
      "answer": "E",
      "rationale": "In a healthy lung anatomic and physiologic dead space are nearly equal because all alveoli are functional. In pathology, non-functional alveoli are ventilated but do not exchange gas, so physiologic dead space can rise to as much as 10 times the anatomic value - up to 1 to 2 liters.",
      "hidden": true
    },
    {
      "question": "Which pair of mechanisms generates the negative intrapleural pressure in a healthy person at functional residual capacity?",
      "options": ["A. Active fluid secretion by mesothelial cells combined with sustained contraction of the visceral pleura during inspiration", "B. Continuous lymphatic drainage of pleural fluid plus the elasticity of the lungs and chest wall", "C. Surfactant reducing alveolar surface tension combined with continuous positive pressure applied along the tracheobronchial tree", "D. Contraction of the diaphragm at rest together with tonic activity of the abdominal wall musculature", "E. Gravity acting on the mediastinal structures together with venous drainage of the bronchial circulation"],
      "answer": "B",
      "rationale": "Slide 20 lists exactly two mechanisms: the lymphatic system drains pleural fluid and generates a negative pressure, and the elasticity of lungs and chest wall creates the opposing recoil forces. At end-expiration the lung's inward recoil and the chest wall's outward recoil are equal and opposite, holding pleural pressure near -5 cm H2O.",
      "hidden": true
    },
    {
      "question": "A patient sustains a stab wound to the left chest and the left lung collapses. Which pressure change most directly explains the collapse?",
      "options": ["A. Alveolar pressure became strongly negative and pulled the lung tissue inward toward the hilum", "B. Airway pressure rose above alveolar pressure and forced gas out of the alveolar compartment", "C. The transairway pressure gradient reversed, driving air from the alveoli back into the conducting airways", "D. Pleural pressure rose toward zero, so transpulmonary pressure fell to zero and elastic recoil collapsed the lung", "E. Intrapleural pressure fell further below atmospheric, increasing the collapsing force on the alveoli"],
      "answer": "D",
      "rationale": "Air entering the pleural space abolishes the negative pleural pressure. Transpulmonary pressure (PA - Ppl) is what holds the lung open; when it becomes zero, the lung's unopposed elastic recoil collapses it. In mild pneumothorax pleural pressure only approaches atmospheric, but in tension pneumothorax it becomes strongly positive.",
      "hidden": true
    }
  ],
  "anking": [
    { "match": "Pulmonary vs alveolar ventilation and dead space", "resources": "Minute ventilation VT x RR; alveolar ventilation (VT - VD) x RR; anatomic vs physiologic dead space" },
    { "match": "Muscles of respiration", "resources": "Diaphragm, external intercostals, parasternal internal intercostals, accessory muscles (SCM, scalenes), abdominal muscles of expiration" },
    { "match": "Intrapleural pressure and lung-chest wall recoil", "resources": "Negative pleural pressure, elastic recoil, transpulmonary pressure, FRC as equilibrium point" },
    { "match": "Pressure-volume changes during the respiratory cycle", "resources": "Alveolar and pleural pressure curves across one breath; Boyle's law" },
    { "match": "Pneumothorax physiology", "resources": "Air in pleural space, transpulmonary pressure zero, tension pneumothorax positive pleural pressure" },
    { "match": "Obstructive vs restrictive lung disease volumes", "resources": "Increased RV and FRC in obstruction; decreased FRC and TLC in restriction" }
  ],
  "ankingResource": {
    "primarySource": "BandB",
    "chapter": "Pulmonary > Pulmonary Physiology > Lung Mechanics and Ventilation",
    "alternatives": [
      { "resource": "Physeo", "chapter": "Respiratory > Physiology > Mechanics of Breathing and Lung Volumes" },
      { "resource": "FirstAid", "chapter": "Respiratory > Physiology > Lung Volumes, Ventilation and Pressure-Volume Curves" },
      { "resource": "Bootcamp", "chapter": "Respiratory > Physiology > Mechanics of Ventilation" },
      { "resource": "Pathoma", "chapter": "Respiratory Tract Pathology > Obstructive vs Restrictive Disease (application of these volumes)" }
    ]
  },
  "pearls": [
    { "title": "Two ventilations, one difference", "content": "Minute (pulmonary) ventilation = VT x RR = 7.5 L/min with this lecture's numbers. Alveolar ventilation = (VT - VD) x RR = 5250 mL/min. The only difference is dead space, and it is the alveolar figure that matters for gas exchange." },
    { "title": "Ventilation mirrors the heart", "content": "Minute ventilation = tidal volume x respiratory rate, exactly parallel to cardiac output = stroke volume x heart rate. Gas instead of liquid, same structure." },
    { "title": "Dead space can multiply tenfold", "content": "Anatomic and physiologic dead space are nearly equal in health because all alveoli are functional. In pathology physiologic dead space can reach 10 times anatomic - 1 to 2 liters - so alveolar ventilation falls even when minute ventilation appears normal." },
    { "title": "The lung floats", "content": "There are no attachments between lung and chest wall except the hilar suspension from the mediastinum. The lung floats in pleural fluid, so pressures - not tethers - determine its volume." },
    { "title": "Bucket and pump", "content": "Bucket handle motion widens the chest laterally; pump handle motion lifts the sternum and deepens it front to back. Inspiration adds at least 20% to anterior-posterior thickness." },
    { "title": "Passive until it is not", "content": "At rest inspiration is active and expiration is passive. In vigorous breathing - exercise, asthma, or altitude - both phases are active, and abdominal muscles join at about 40 L/min, SCM and serratus anterior at 50, spinal erectors and trapezius at 100. Disease recruits all of them far earlier." },
    { "title": "Why pleural pressure is negative", "content": "Two reasons only: lymphatics continuously drain pleural fluid, and lung recoil inward is balanced against chest wall recoil outward. The pleural space is 5 to 35 microns wide and behaves as a relative vacuum at FRC." },
    { "title": "The pressure cycle in nine numbers", "content": "Intrapleural: -5, -8, -5. Alveolar: 0, -1, 0, +1, 0. Atmospheric is always zero. Only alveolar pressure ever becomes positive, and that positive value is what expels air." },
    { "title": "Transpulmonary is a subtraction, not an event", "content": "PL = PA - Ppl, the elastic recoil pressure of the lung. It is the vertical gap between the two pressure curves and is largest at end-inspiration (-1 minus -8 = +7), when the stretched lung recoils hardest." },
    { "title": "One sign flips the diagnosis", "content": "Obstructive disease cannot develop positive alveolar pressure, so air is trapped and RV and FRC rise. Restrictive disease cannot develop negative alveolar pressure, so the lung underfills and FRC and TLC fall." },
    { "title": "The pleural space tolerates nothing extra", "content": "Air gives pneumothorax (transpulmonary pressure to zero, lung collapse, strongly positive pleural pressure if tension); fluid gives an effusion treated by thoracentesis. Withdraw the needle carefully so air is not trapped inside." },
    { "title": "FRC is where the tug of war ties", "content": "Expiration continues until lung recoil force decreases to again equal intrapleural pressure - that point is FRC. FRC = RV + ERV, and it falls with ascites, pregnancy, obesity and paradoxical diaphragm movement." }
  ],
  "mindmap": `
## Lung Mechanics: Pressures Acting on the System

### Ventilation

- **Pulmonary (minute) ventilation**: VT x RR = 500 mL x 15 = 7.5 L/min
- **Alveolar ventilation**: (VT - VD) x RR = 350 x 15 = 5250 mL/min
- **Dead space**: anatomic ~150 mL; physiologic = anatomic in health; up to 10x (1-2 L) in disease
- **Cardiac parallel**: CO = SV x HR
- **Volumes/capacities**: TV, IRV, ERV, RV; IC, VC, FRC, TLC
- **Igloo analogy**: one pipe in and out, unlike heart and gut

### Muscles of Respiration

- **Two maneuvers**: diaphragm up/down; ribs elevate/depress (A-P diameter)
- **Diaphragm**: flattens on inspiration, domes on expiration; most important muscle
- **Principal inspiratory**: external intercostals, interchondral part of internal intercostals, diaphragm
- **Accessory inspiratory**: sternocleidomastoid, scalenes
- **Expiratory (when active)**: internal intercostals, rectus abdominis, obliques, transversus abdominis
- **Bucket handle**: lateral volume increase
- **Pump handle**: anterior volume increase; AP thickness up at least 20%
- **Mechanical advantage**: rostral/dorsal external + parasternal internal = inspiratory; caudal internal, caudal-ventral external, transversus thoracis = expiratory
- **Recruitment**: abdominals 40 L/min; SCM + serratus anterior 50; spinal erectors + trapezius 100; earlier in disease
- **Rest vs vigorous**: inspiration active + expiration passive at rest; both active in vigorous breathing (exercise, asthma, altitude 5630 m)

### Diaphragm Dysfunction

- **Causes**: paradoxical movement, ascites, pregnancy, obesity
- **Consequence**: FRC decreases
- **FRC**: RV + ERV

### Intrapleural Pressure

- **Average**: -5 cm H2O; more negative at apex than base
- **Cause of gradient**: gravity and posture; vanishes in microgravity
- **Space**: visceral + parietal pleura, 5-35 microns, relative vacuum at FRC
- **Negativity source 1**: lymphatic drainage of pleural fluid
- **Negativity source 2**: elasticity of lung (inward) vs chest wall (outward) - tug of war
- **Units**: cm H2O (water manometers more sensitive; mercury hazardous)

### Alveolar Pressure and the Breath Cycle

- **Boyle's law**: P1V1 = P2V2 at constant temperature
- **Rest/FRC**: PA 0, Ppl -5, no airflow, recoil equal and opposite
- **Inspiration**: muscles contract -> Ppl -5 to -8 -> lung expands -> PA 0 to -1 -> air in
- **Expiration**: muscles relax -> Ppl -8 to -5 -> lung shrinks -> PA 0 to +1 -> air out -> PA back to 0
- **Endpoint**: recoil force again equals intrapleural pressure = FRC

### Transpulmonary Pressure

- **Definition**: PL = PA - Ppl (inside minus outside; outside is always pleural)
- **Meaning**: elastic recoil pressure of the lungs
- **Values**: +5 at rest, +7 at end-inspiration (largest)
- **Related pressures**: Paw, PA, Ppl, PL, Pta
- **Summary**: outward chest wall recoil opposed by inward lung recoil; air flows only down pressure gradients

### Pleural Pathology

- **Pneumothorax**: air in pleural space; Ppl less negative; PL to zero; lung collapses
- **Tension pneumothorax**: Ppl strongly positive
- **Protection**: mediastinal membrane keeps the other lung inflated
- **Causes**: stab, trauma, post-cardiothoracic surgery
- **Pleural effusion**: excess fluid; no visible air at the base on x-ray
- **Thoracentesis**: pleural tapping; drain slowly; avoid trapping air on withdrawal

### Obstructive vs Restrictive

- **Obstructive (asthma, chronic bronchitis)**: cannot develop + alveolar pressure; RV and FRC increased
- **Restrictive (pulmonary fibrosis)**: cannot develop - alveolar pressure; FRC, TLC, RV, ERV, TV decreased
- **Quick quiz (Slide 36)**: pleural pressure reaches -8 cm H2O as inspiration proceeds, because rising lung recoil must be opposed
`
});
