window.receiveLectureContent({
  "id": "cv47",
  "title": "Lecture #47: Physiology - Airways and Pulmonary Blood Flow",
  "lecturer": "Joerg R. Leheste, Ph.D., M.Sc.",
  "pdf": "content/CV47_HighYield_Render.pdf",
  "content": `
# Lecture #47: Physiology - Airways and Pulmonary Blood Flow

**Lecturer:** Joerg R. Leheste, Ph.D., M.Sc.
**Session:** Lecture #47

## Orientation (Slides 1-2)

This opens the respiratory physiology series, and the lecturer states his rules up front: the objectives define the scope, "no more, no less," and nearly every one of them is a **structure-function relationship** (Slide 2). He wants concepts, not "rogue knowledge," so almost every fact below is the answer to a *why*. One objective is unusual and he means it literally - describe how **socio-economic determinants of health** affect a person's ability to breathe. The lecture therefore runs from the trachea down to a single water molecule on the alveolar surface, and detours through a child's apartment on the way.

## Two Respirations, and the Fate of CO2 (Slides 3-4)

"Respiration" names two opposite events at opposite ends of the same bloodstream. **External respiration** is gas exchange in the alveolus: CO2 leaves the blood as waste and O2 is taken up. **Internal respiration** is the mirror image at the target tissue - a working muscle, for instance - where that O2 is handed off and the CO2 generated by the tissue's work is dumped into the blood for disposal. The lecturer's specific complaint is that gas exchange gets taught as an oxygen story; CO2 matters just as much, and how the blood carries it is what ties respiration to acid-base balance [[CV14]].

- **Three fates of CO2 once it crosses the interstitial fluid into the capillary (Slide 4):**
  - **Bound directly to red blood cells** and carried to the lungs that way.
  - **Dissolved in the blood** and carried in solution.
  - **Converted to bicarbonate - the majority route**, which is the **bicarbonate buffer system** that buffers our blood.
    - CO2 enters the red blood cell and is **combined with water into carbonic acid**; a proton then splits off, leaving **bicarbonate**.
    - **Carbonic anhydrase** catalyzes both steps, is **tied to the red blood cell**, and **runs in both directions** - which is why the same enzyme can reverse the reaction at the lung [Lecturer Emphasis].

## The Respiratory Tree: Two Zones, One Boundary (Slides 5-6)

Everything below the nasopharynx is the respiratory tree: it begins at the **trachea (generation 0, at the level of the 3rd or 4th thoracic vertebra)** and ends at the **alveolar sacs (generation 23)**. The single most important structural fact is that the tree is split into two functional halves. Conduction of air happens **down to generation 16 without any participation in gas exchange**; everything **below generation 16** is where gas exchange occurs. That boundary sits at the **terminal bronchioles**, and once you know where it is, the presence or absence of cartilage, cilia and smooth muscle all become predictable.

- **Cartilage (Slides 5-6):** rings around the trachea and patches on the bronchi hold the **large conducting airways open**. Cartilage support **stops at generation 10** (Slide 5); the smaller bronchi are the last structures that have it. Past that point, patency depends on airway tone, not on a skeleton.
- **Smooth muscle:** wrapped around **almost the entire system, all the way down into the alveolar ducts**, and wrapped **tightly around the bronchioles down to the terminal bronchioles** (Slide 14). Airflow can therefore be regulated at every one of those levels - and that is exactly where asthma does its damage.
- **Cilia:** present **all the way down into the respiratory bronchioles**, sweeping inhaled dust, debris and pathogens back up.
- **Surface area:** as the tree moves from the conducting into the respiratory zone the tubes get smaller but the **total surface area increases tremendously** - the unfolded human lung is roughly the size of a **tennis court** (Slide 11). The bigger the surface, the easier the gas exchange.

:::diagram cv47-airway-generations:::

:::highyield
Three numbers carry this lecture's anatomy: **cartilage stops at generation 10**, the **conducting zone ends at generation 16 (terminal bronchiole)**, and the tree **ends at generation 23 (alveolar sacs)**.
:::

## The Conducting Zone Does Three Jobs (Slide 7)

Air arriving from outside is cold, dry and dirty, and none of those states is compatible with a delicate alveolar membrane. The conducting zone fixes all three on the way down, and the third fix is a mechanical conveyor belt rather than an immune response: debris, dust and pathogens **dissolve in the mucus** lining the airway, and the cilia **beat that mucus upward**, after which it is swallowed, coughed out, or blown out through the nose. That is the **mucociliary elevator** (also called mucociliary clearance), and it is how the system stays clean and pathogen-free.

:::mnemonic
**Conducting zone: three jobs**
**WHF**

- **W:** Warm the incoming air
- **H:** Humidify it
- **F:** Filter it - mucus traps, cilia sweep, mucociliary elevator carries it up
  :::

## Autonomic Regulation of Airway Caliber (Slides 8-9)

Breathing runs without conscious effort because airway smooth muscle is under **autonomic** control, and the two divisions do exactly opposite things to the same ring of muscle. The **sympathetic** division emerges from spinal levels **T1-T4** and acts through **beta-2 adrenergic receptors** to **widen** the airway - which makes sense, because fight-or-flight demands more air. The **parasympathetic** division travels in the **vagus nerve (cranial nerve X)** and acts through **muscarinic acetylcholine receptors** to **narrow** it.

- **Beta-2 agonists used therapeutically (Slide 8):** **epinephrine, isoproterenol, albuterol** - the drugs anyone familiar with asthma already knows, given precisely to widen airway diameter.
- **Bronchoconstriction ranges from bothersome to life-threatening** and can be set off by (Slide 9): **allergies** in most cases, **viral infections**, and **gastroesophageal reflux disease**.

:::diagram cv47-airway-tone:::

:::correlate
Asthma

- **Pathophysiology:** the smooth muscle fibers wrapped around the bronchioles and terminal bronchioles undergo **undue contraction**, closing off airways and impeding airflow (Slide 14). Because those airways have **no cartilage support past generation 10**, there is nothing to hold them open once the muscle contracts.
- **Presentation:** episodic cough, wheeze, shortness of breath and chest tightness; in the acute severe attack, shortness of breath with chest pain and a wheezing cough.
- **Treatment:** beta-2 agonists - **albuterol, epinephrine, isoproterenol** - to reverse the constriction (Slide 8).
- **Risk Factors / Triggers:** allergens, viral infection, reflux, and **poor-quality, hot indoor air** (Slide 10).
- **Lecturer's Point:** this is the clinical payoff of the anatomy slide. "That is exactly what happens when the system gets irritated, for instance with allergens - these smooth muscle fibers contract and close off those airways" [Lecturer Emphasis].
  :::

:::correlate
Allergic Rhinitis

- **Pathophysiology:** the same allergic process acting on the upper airway mucosa rather than on bronchiolar smooth muscle; it accompanies asthma in the lecture's case (Slide 10).
- **Presentation:** **itchy, red, watery eyes** and a **stuffy, runny nose**, present for more than a year alongside the episodic lower-airway symptoms.
- **Lecturer's Point:** the upper- and lower-airway findings are one disease process in one environment - do not treat them as coincidental.
  :::

:::correlate
Gastroesophageal Reflux Disease as an Airway Trigger

- **Pathophysiology:** excess stomach acid reaches the respiratory tree, **damages and irritates** the mucosa, and that irritation triggers **bronchoconstriction** through the muscarinic pathway (Slide 9).
- **Lecturer's Point:** reflux belongs on the differential for a wheezing patient with no allergic history - the airway does not care where the irritant came from.
  :::

:::correlate
Post-Viral Airway Disease (including Long COVID)

- **Pathophysiology:** viral infection of the airway is one of the depicted triggers of bronchoconstriction (Slide 9).
- **Lecturer's Point:** "a lot of long COVID that we see right now is due to the effect of the COVID-19 virus during infection" - persistent airway symptoms after a viral illness are the same smooth-muscle problem, not a separate mechanism [Lecturer Emphasis].
  :::

## Socio-Economic Determinants of Health (Slide 10)

The lecturer reads this slide aloud rather than summarizing it, to make the point that **resources sit at the center of health and health care**. Dylan is a **7-year-old African American boy** brought to a large medical center's emergency department with severe shortness of breath, chest pain and a wheezing cough; his mother is crying and afraid he will asphyxiate. He has had milder versions of the same symptoms, plus allergic eye and nose symptoms, for over a year. The family - mother, Dylan, and one younger sibling - lives in a **one-bedroom apartment in Washington Heights**; the mother sleeps on the couch, has **cut her bakery hours because of childcare**, is **behind on rent**, and her **landlord will not repair the window air conditioning unit**, leaving the children in **hot, low-quality air** through the summer. That housing failure is the proximate trigger of the attack.

:::highyield
The pharmacology treats the bronchospasm; the **broken air conditioner is the actual etiology**. Housing quality, income, childcare access and landlord accountability are modifiable determinants of an asthma exacerbation, and the exam-relevant skill is naming them as causes rather than as background (Slide 10).
:::

## The Respiratory Zone and the Alveolus (Slides 11-12)

Below generation 16 the job changes from moving air to exchanging gas, and the design is optimized for diffusion: enormous area, minimal distance. Gas moves from the **alveolar airspace** into the **interstitial fluid** and then into the **nearby capillary**, which means CO2 and O2 must cross **two cell layers - the pneumocyte and the capillary endothelial cell - plus a layer of liquid**. The lecturer flags this as remarkable rather than trivial: it works only because the distances are so small and the surface is so large.

- **Scale (Slide 12):** roughly **300 million alveoli per lung**.
- **Type I pneumocytes (~90%):** **lining cells**; metabolically **not very active**.
- **Type II pneumocytes (~10%):** the metabolically active ones. Two jobs:
  - They contain **lamellar bodies** and release **surfactant** through them.
  - They are the **stem cells of the alveolus** - if either a type I or a type II cell is damaged, the replacement comes from the type II pool.

## Two Circulations, One Lung (Slides 13-15)

The body runs **two separate circulatory systems**, and the lung is the one organ served by both. The **pulmonary circuit** serves only the lungs and is deliberately a **low-pressure** system, while the **systemic circuit** runs at high pressure. The reason is structural: the gas-exchange surfaces are tiny and delicate, and a high-pressure pulmonary circuit would do two harmful things - blood would move too fast to **allow enough time for gas exchange**, and the pressure would **destroy the system**. But the thick walls of the trachea and the large bronchi cannot live on diffusion from the air they conduct, so they need a high-pressure supply of their own: the **bronchial circulation**, which is part of the systemic circuit.

| Feature | Pulmonary circulation (Slides 13-14) | Bronchial circulation (Slide 15) |
| --- | --- | --- |
| Pressure | Low | High |
| Belongs to | Pulmonary circuit | Systemic circuit |
| Origin | Right ventricle | Aorta |
| Vessels | Pulmonary artery, pulmonary vein | Bronchial arteries and veins, arterioles and venules |
| Blood in the artery | **Oxygen-poor** | Oxygen-rich |
| Purpose | Gas exchange at the alveolus | Nourish the conducting airway walls |

- The **pulmonary artery is the only artery in the body that carries blood low in oxygen**, and it originates from the **right ventricle**; oxygen-rich blood returns to the heart through the **pulmonary vein**.
- The **bronchial arteries branch from the aorta**, not from the right ventricle - so there is no "redundant backup" between the two systems.
- Diffusion of oxygen is a **function of distance**: the segmental bronchi are simply too thick to be fed by oxygen diffusing out of the pulmonary circulation, which is the whole reason a second supply exists [Lecturer Emphasis].

:::mnemonic
**Which vessel carries what**
**PA is Poor, PV is Plush**

- **PA:** Pulmonary Artery - the one artery carrying oxygen-POOR blood, out of the right ventricle
- **PV:** Pulmonary Vein - oxygen-RICH blood back to the heart, slightly diluted by the bronchial shunt
  :::

## Shunts: Where the Two Systems Touch (Slide 16)

A **shunt** is a connection between two systems that are otherwise separate - and having just learned why pulmonary and systemic circulation must stay apart, the lecturer immediately shows where they do not. Deoxygenated blood arrives in the pulmonary artery, is oxygenated at the alveolus, and then meets a vessel from the bronchial system that adds **oxygen-poor blood into the freshly oxygenated stream**. This junction is the **bronchopulmonary anastomosis**, and about **two-thirds of the bronchial blood supply drains this way**. The consequence follows immediately: blood oxygen concentration **before** the anastomosis is **higher** than after it, so the bronchial contribution makes blood leaving the lung slightly less oxygenated than blood leaving an alveolus.

:::diagram cv47-bronchopulmonary-shunt:::

## Surface Tension, the Laplace Law, and Surfactant (Slides 17-20)

Water always tries to reach its **lowest volume**, and it does so through **surface tension** - water molecules stick to one another. Inside the alveolus, look at where a given water molecule sits. A molecule in the middle of the film pulls equally in all directions on its neighbors. A molecule **at the air-liquid boundary has nothing to bond with on the air side**, so it forms **more bonds inward**, toward the water. That unbalanced inward pull, summed over the whole lining, is the **force that collapses the alveolus**, and it is what the Laplace law describes.

- **Laplace law (Slide 18):** the pressure driving collapse is **P = 2T / r**, where T is the surface tension of the lining fluid and r is the alveolar radius.
- **The collapsing pressure is inversely proportional to the radius:**
  - **Smaller alveolus** -> water molecules closer together -> **higher pressure to collapse**.
  - **Larger alveolus** -> water molecules farther apart -> **lower pressure to collapse**.
- **Surfactant is the molecule that prevents the collapse:**
  - Made by **type II pneumocytes** and released from lamellar bodies (Slide 12).
  - Chemically it is **dipalmitoyl phosphatidylcholine (DPPC)**, a **phospholipid** (Slide 20).
  - It **inserts between the water molecules and breaks up the surface tension** - functionally and chemically, it behaves like **soap**.
  - Two stated consequences (Slide 18): it **increases compliance** of the alveolar spaces and **prevents over-wetting**.

:::diagram cv47-laplace-surfactant:::

## The Lecturer's Own Practice Question (Slide 21)

An animal model has the **pulmonary artery to the left lung occluded** while the **bronchial arteries are left intact**. Gas exchange in that lung falls to near zero, yet the structural tissues of the conducting airways stay healthy. The answer is that the **bronchial circulation branches from the systemic arterial tree and delivers oxygenated blood directly to the walls of the conducting airways**. The lecturer's real instruction, though, was about method: do not only learn the right answer, work out why each distractor fails, because that is what hinges the fact to the broader context [Lecturer Emphasis].

- **"Bronchial arteries reversed their flow"** - that flow reversal never happens.
- **"Pulmonary circulation is high-pressure for tissue nutrition"** - exactly backwards; pulmonary is low-pressure for gas exchange, bronchial is the nutritive supply.
- **"Alveolar capillaries feed the thick bronchial walls"** - diffusion is a function of distance, and those walls are far too thick.
- **"Both systems originate from the right ventricle"** - only the pulmonary artery does; the bronchial arteries come off the aorta.

:::highyield
Occlude the pulmonary artery and you lose gas exchange, not airway viability. Occlude the bronchial supply and the airway walls starve while gas exchange continues. That dissociation is the cleanest test of whether you actually understand the two circulations (Slide 21).
:::
`,
  "flashcards": [
    { "front": "Define external versus internal respiration.", "back": "External respiration is gas exchange in the alveoli: CO2 released from blood as waste, O2 taken up into the bloodstream. Internal respiration is the reverse at the target tissue: O2 handed off to the tissue and CO2 from that tissue's work released into the blood for disposal.", "tag": "Glossary" },
    { "front": "What are the three fates of CO2 carried in blood, and which predominates?", "back": "Bound directly to red blood cells; dissolved in the blood; or converted into bicarbonate as part of the bicarbonate buffer system, which is the majority route. CO2 plus water becomes carbonic acid, a proton splits off, and bicarbonate remains.", "tag": "Concept" },
    { "front": "Why is carbonic anhydrase tied to the red blood cell important?", "back": "It catalyzes both steps of the bicarbonate reaction and runs in both directions, so the same enzyme that generates bicarbonate at the tissue can reverse the reaction at the lung to release CO2.", "tag": "Concept" },
    { "front": "At which generation does the conducting zone end, and what structure marks it?", "back": "Generation 16, the terminal bronchiole. Conduction occurs down to generation 16 without gas exchange; everything below it, out to generation 23 (alveolar sacs), is the respiratory zone where gas exchange occurs.", "tag": "Glossary" },
    { "front": "Where does cartilage support end, and why does that matter clinically?", "back": "At generation 10 - the smaller bronchi are the last cartilage-supported structures. Beyond that, patency depends on smooth muscle tone, which is why bronchoconstriction can close those airways completely.", "tag": "Concept" },
    { "front": "What are the three functions of the conducting zone, and what is the mucociliary elevator?", "back": "Humidify, warm and (most importantly) filter. Debris, dust and pathogens dissolve in the airway mucus and cilia beat that mucus upward to be swallowed, coughed out or blown out - the mucociliary elevator, also called mucociliary clearance.", "tag": "Concept" },
    { "front": "Compare the sympathetic and parasympathetic control of airway diameter.", "back": "Sympathetic: spinal levels T1-T4, beta-2 adrenergic receptors, bronchodilation (epinephrine, isoproterenol, albuterol) - fits fight-or-flight. Parasympathetic: vagus nerve (CN X), muscarinic acetylcholine receptors, bronchoconstriction.", "tag": "Concept" },
    { "front": "Name the three triggers of bronchoconstriction given in this lecture.", "back": "Allergies (the majority of cases), viral infections (the lecturer cites long COVID), and gastroesophageal reflux disease, where acid reaching the respiratory tree causes irritation and damage.", "tag": "Clinical" },
    { "front": "Contrast type I and type II pneumocytes.", "back": "Type I are about 90% of the lining, are simple lining cells and are not metabolically very active. Type II are about 10%, contain lamellar bodies and release surfactant, and are the stem cells of the alveolus that replace damaged type I or type II cells.", "tag": "Glossary" },
    { "front": "What layers must O2 and CO2 cross between the alveolar airspace and the capillary?", "back": "Two cell layers - the pneumocyte and the capillary endothelial cell - plus a layer of liquid (the interstitial fluid). It works because the distances are tiny and the total surface area is enormous, roughly a tennis court for the unfolded lung.", "tag": "Concept" },
    { "front": "Why must the pulmonary circulation be a low-pressure system?", "back": "The gas-exchange structures are very small and delicate. A high-pressure system would not allow enough time for gas exchange and would physically destroy the alveolar structures.", "tag": "Concept" },
    { "front": "What is the bronchial circulation, where does it arise, and what does it do?", "back": "A high-pressure system that is part of the systemic circulation, arising from the aorta. Bronchial arteries, veins, arterioles and venules feed the tissues of the larger portions of the respiratory tree - walls too thick to take oxygen by diffusion from the air they conduct.", "tag": "Concept" },
    { "front": "What is a bronchopulmonary anastomosis and what is its consequence?", "back": "A shunt joining the bronchial (systemic) and pulmonary circulations; about two-thirds of bronchial blood drains this way. Oxygen-poor bronchial blood is added to freshly oxygenated blood, so blood oxygen content downstream of the anastomosis is slightly lower than upstream.", "tag": "Concept" },
    { "front": "State the Laplace law as taught here and its physiologic implication.", "back": "The collapsing pressure P = 2T/r, so it is inversely proportional to the alveolar radius. The smaller the alveolus, the closer the water molecules and the higher the pressure to collapse; larger alveoli have a lower collapsing pressure.", "tag": "Concept" },
    { "front": "What is surfactant chemically, who makes it, and how does it work?", "back": "Dipalmitoyl phosphatidylcholine (DPPC), a phospholipid, released from lamellar bodies of type II pneumocytes. It inserts between water molecules and breaks up surface tension like soap, which increases compliance and prevents over-wetting.", "tag": "Concept" }
  ],
  "questions": [
    {
      "question": "A researcher traces an inhaled particle down the respiratory tree and notes the exact point at which gas exchange first becomes possible. Which structure marks that transition?",
      "options": ["A. Segmental bronchus", "B. Trachea at generation 0", "C. Alveolar sac at generation 23", "D. Terminal bronchiole at generation 16", "E. Last cartilage-containing bronchus"],
      "answer": "D",
      "rationale": "Conduction occurs down to generation 16 without any participation in gas exchange, and gas exchange occurs in all structures below level 16 (Slide 5). Generation 16 is the terminal bronchiole. Cartilage stopping at generation 10 is a separate landmark, and generation 23 is the end of the tree, not the start of exchange.",
      "hidden": true
    },
    {
      "question": "A 7-year-old with a one-year history of episodic wheeze presents with severe shortness of breath and a wheezing cough after a summer in an apartment with a broken air conditioner. Which structural feature best explains why his small airways can close completely?",
      "options": ["A. Loss of ciliated epithelium below the respiratory bronchioles", "B. Absence of cartilage support beyond generation 10, leaving patency to smooth muscle tone", "C. Reduced total cross-sectional area in the respiratory zone", "D. Failure of type II pneumocytes to release surfactant into the airway", "E. Collapse of the pulmonary artery under systemic pressure"],
      "answer": "B",
      "rationale": "Cartilage rings and patches keep the large conducting airways open, but that support stops at generation 10 (Slide 5). Smooth muscle is wrapped around almost the whole system down into the alveolar ducts, so beyond the cartilage the airway is held open only by muscle tone - and undue contraction of that muscle closes the lumen (Slide 14).",
      "hidden": true
    },
    {
      "question": "An investigator measures oxygen content in blood sampled immediately downstream of an alveolar capillary and again in the pulmonary vein. The second value is slightly lower. What accounts for the difference?",
      "options": ["A. Oxygen consumption by type I pneumocytes lining the alveolus", "B. Incomplete diffusion across the two cell layers and fluid layer of the barrier", "C. Bronchial venous blood entering through bronchopulmonary anastomoses", "D. Reversal of flow in the pulmonary artery during diastole", "E. Binding of oxygen to carbonic anhydrase within red blood cells"],
      "answer": "C",
      "rationale": "About two-thirds of the bronchial blood supply drains into the pulmonary circuit through bronchopulmonary anastomoses (Slide 16). That blood is systemic venous blood and is oxygen-poor, so adding it to freshly oxygenated blood lowers the oxygen content downstream. Blood oxygen concentration before the anastomosis is higher than after it.",
      "hidden": true
    },
    {
      "question": "Two alveoli in the same lung are lined by fluid of identical surface tension, but one has half the radius of the other. Which statement about the smaller alveolus is correct?",
      "options": ["A. It has a lower collapsing pressure because it contains less lining fluid overall", "B. Its collapsing pressure is unchanged, since pressure depends only on surface tension", "C. It has a higher collapsing pressure because water molecules are packed closer together", "D. It has a higher collapsing pressure because it contains proportionally more surfactant", "E. Its collapsing pressure rises only when the lining fluid loses its phospholipid content"],
      "answer": "C",
      "rationale": "By the Laplace law the collapsing pressure equals 2T/r and is therefore inversely proportional to the radius (Slide 18). The smaller the alveolus, the closer the water molecules are to each other and the higher the pressure driving collapse. The larger the alveolus, the farther apart they are and the lower that pressure.",
      "hidden": true
    },
    {
      "question": "In an animal model the pulmonary artery to the left lung is occluded while the bronchial arteries are left patent. Gas exchange in that lung falls to near zero, yet the walls of the conducting airways remain viable. Which concept explains the survival of those tissues?",
      "options": ["A. The pulmonary artery normally delivers oxygen-rich blood, and bronchial flow reversed to compensate", "B. Alveolar capillaries fed by the pulmonary artery are the primary oxygen source for thick bronchial walls", "C. Both arterial systems arise from the right ventricle and provide redundant nutrient delivery to the lung", "D. The pulmonary circulation is high-pressure and nutritive while bronchial flow serves only alveolar exchange", "E. The bronchial circulation arises from the systemic arterial tree and oxygenates the conducting airway walls"],
      "answer": "E",
      "rationale": "The bronchial circulation is a high-pressure system, part of the systemic circulation, arising from the aorta, and its function is to feed the tissues of the larger portions of the respiratory tree that are too thick to take oxygen from the air they conduct (Slide 15). The pulmonary artery carries oxygen-poor blood at low pressure and originates from the right ventricle, so none of the other options survive scrutiny (Slide 21).",
      "hidden": true
    }
  ],
  "anking": [
    { "match": "Conducting zone versus respiratory zone", "resources": "Generations 0-16 conducting, terminal bronchiole boundary, generations 17-23 respiratory, cartilage to generation 10" },
    { "match": "Mucociliary clearance", "resources": "Mucociliary elevator, warm humidify filter, cilia to respiratory bronchioles" },
    { "match": "Autonomic control of airway smooth muscle", "resources": "Beta-2 adrenergic bronchodilation, albuterol, muscarinic vagal bronchoconstriction" },
    { "match": "Type I and type II pneumocytes", "resources": "Type I 90% lining, type II 10% lamellar bodies, surfactant, alveolar stem cell" },
    { "match": "Surfactant and the Laplace law", "resources": "DPPC dipalmitoyl phosphatidylcholine, surface tension, P = 2T/r, compliance" },
    { "match": "Pulmonary versus bronchial circulation", "resources": "Low-pressure pulmonary circuit, pulmonary artery carries deoxygenated blood, bronchial arteries from the aorta" },
    { "match": "Physiologic shunt", "resources": "Bronchopulmonary anastomosis, 2/3 of bronchial venous drainage, small fall in blood oxygen content" },
    { "match": "Social determinants of health and asthma", "resources": "Housing quality, indoor air, income and childcare as asthma triggers" }
  ],
  "ankingResource": {
    "primarySource": "BandB",
    "chapter": "Pulmonary > Lung Anatomy and Mechanics > Airways, Alveoli and Surfactant",
    "alternatives": [
      { "resource": "Physeo", "chapter": "Physiology > Respiratory > Lung Anatomy and Surfactant" },
      { "resource": "FirstAid", "chapter": "Respiratory > Anatomy and Physiology > Respiratory Tree, Pneumocytes, Surfactant" },
      { "resource": "Bootcamp", "chapter": "Physiology > Respiratory > Airway Structure and Pulmonary Circulation" },
      { "resource": "Pixorize", "chapter": "Physiology > Respiratory > Surfactant and Alveolar Cells" }
    ]
  },
  "pearls": [
    { "title": "Generation 16 is the line", "content": "Conduction runs from the trachea (generation 0) to generation 16, the terminal bronchiole, with no gas exchange. Everything below generation 16 out to generation 23 exchanges gas. Cartilage stops earlier, at generation 10." },
    { "title": "No cartilage, no scaffold", "content": "Past generation 10 the airway has no cartilage and is held open by smooth muscle tone alone. That is the anatomic reason bronchoconstriction can close small airways completely while the trachea stays open." },
    { "title": "The mucociliary elevator", "content": "Filtration is mechanical: dust, debris and pathogens dissolve in airway mucus and cilia - present down to the respiratory bronchioles - beat that mucus upward to be swallowed or expelled." },
    { "title": "Opposite divisions, one muscle", "content": "Sympathetic T1-T4 acts on beta-2 receptors to dilate (epinephrine, isoproterenol, albuterol); parasympathetic vagus (CN X) acts on muscarinic receptors to constrict. Fight-or-flight opens the airway because fight-or-flight needs air." },
    { "title": "Three triggers of bronchoconstriction", "content": "Allergies in most cases, viral infection (the lecturer's example is long COVID), and gastroesophageal reflux, where acid reaching the respiratory tree irritates and damages the mucosa." },
    { "title": "Type II does everything", "content": "Type II pneumocytes are only about 10% of the alveolar lining, but they hold the lamellar bodies that release surfactant and they are the stem cells that replace damaged type I and type II cells. Type I cells are 90% of the lining and are metabolically quiet." },
    { "title": "The barrier is thin, the sheet is huge", "content": "Gases cross two cell layers - pneumocyte and capillary endothelial cell - plus a layer of liquid. It works only because the distances are minute and the unfolded lung is about the size of a tennis court, with roughly 300 million alveoli per lung." },
    { "title": "Low pressure is a design requirement", "content": "The pulmonary circuit is deliberately low-pressure for two reasons: high pressure would push blood past the alveolus too fast to allow gas exchange, and it would destroy the delicate exchange structures." },
    { "title": "The one artery that is not red", "content": "The pulmonary artery is the only artery in the body carrying oxygen-poor blood, and it originates from the right ventricle. The bronchial arteries come off the aorta, so the two systems are not redundant backups for each other." },
    { "title": "Diffusion is a function of distance", "content": "The walls of the main and segmental bronchi are far too thick to be oxygenated by diffusion from the air in the lumen or from the pulmonary circulation - which is exactly why a separate high-pressure bronchial supply exists." },
    { "title": "The shunt costs you a little oxygen", "content": "About two-thirds of bronchial venous blood drains into the pulmonary circuit through bronchopulmonary anastomoses. Because it is systemic venous blood, oxygen content downstream of the anastomosis is slightly lower than immediately after gas exchange." },
    { "title": "Small alveoli are the fragile ones", "content": "Collapsing pressure P = 2T/r is inversely proportional to radius, so the smallest alveoli face the strongest collapsing force. Surfactant is what keeps them from emptying into their larger neighbours." },
    { "title": "Surfactant is soap", "content": "Dipalmitoyl phosphatidylcholine (DPPC) is a phospholipid that inserts between the water molecules of the alveolar lining and breaks up surface tension exactly the way soap does - raising compliance and preventing over-wetting." },
    { "title": "Name the determinant, not just the trigger", "content": "In the lecture's case the asthma attack traces to hot, low-quality indoor air from an unrepaired air conditioner, itself traceable to unpaid rent, reduced work hours and unavailable childcare. Housing and income are the etiology; the bronchodilator only treats the endpoint." }
  ],
  "mindmap": `
## Airways and Pulmonary Blood Flow

### Respiration: Two Directions

- **External respiration**: gas exchange in alveoli; CO2 out of blood, O2 into blood
- **Internal respiration**: at target tissue; O2 to tissue, CO2 into blood
- **CO2 fate 1**: bound directly to red blood cells
- **CO2 fate 2**: dissolved in blood
- **CO2 fate 3 (majority)**: bicarbonate buffer system
- **Carbonic anhydrase**: tied to the red blood cell, catalyzes both steps, runs in both directions

### Respiratory Tree

- **Generation 0**: trachea, at the 3rd or 4th thoracic vertebra
- **Generation 10**: cartilage support stops; smaller bronchi are the last with cartilage
- **Generation 16**: terminal bronchiole; conducting zone ends
- **Generation 23**: alveolar sacs; end of the tree
- **Cartilage**: rings and patches keeping large conducting airways open
- **Smooth muscle**: almost the whole tree, down into the alveolar ducts
- **Cilia**: down to the respiratory bronchioles
- **Surface area**: rises sharply into the respiratory zone; unfolded lung about a tennis court

### Conducting Zone

- **Function 1**: humidify incoming air
- **Function 2**: warm incoming air
- **Function 3**: filter - most important
- **Mucociliary elevator**: debris dissolves in mucus, cilia beat it upward, swallowed or expelled

### Autonomic Regulation

- **Sympathetic**: spinal cord T1-T4, beta-2 adrenergic receptors, bronchodilation
- **Beta-2 agonists**: epinephrine, isoproterenol, albuterol
- **Parasympathetic**: vagus nerve (CN X), muscarinic acetylcholine receptors, bronchoconstriction
- **Severity**: bronchoconstriction ranges from bothersome to life-threatening
- **Trigger - allergy**: most cases
- **Trigger - viral infection**: long COVID cited
- **Trigger - GERD**: acid reaches the respiratory tree, irritation and damage

### Socio-Economic Determinants of Health

- **Case**: 7-year-old boy, severe shortness of breath, chest pain, wheezing cough
- **Chronic symptoms**: episodic cough, wheeze, dyspnea, chest tightness over one year
- **Allergic rhinitis**: itchy red watery eyes, stuffy runny nose
- **Housing**: one-bedroom apartment, Washington Heights, mother sleeps on the couch
- **Economics**: reduced bakery hours from childcare issues, behind on rent
- **Proximate trigger**: landlord will not repair the window air conditioner; hot low-quality air

### Respiratory Zone and Alveolus

- **Scale**: about 300 million alveoli per lung
- **Barrier**: alveolar air to interstitial fluid to capillary
- **Layers crossed**: pneumocyte, capillary endothelial cell, plus a layer of liquid
- **Type I pneumocyte**: about 90%, lining cell, metabolically not very active
- **Type II pneumocyte**: about 10%, lamellar bodies, releases surfactant
- **Type II second role**: stem cell of the alveolus, replaces damaged type I and type II cells

### Pulmonary Circulation

- **Pressure**: low, by design
- **Reason 1**: high pressure would not allow enough time for gas exchange
- **Reason 2**: high pressure would destroy the delicate exchange structures
- **Pulmonary artery**: only artery carrying oxygen-poor blood; from the right ventricle
- **Pulmonary vein**: returns oxygen-rich blood to the heart
- **Smooth muscle**: wrapped tightly around bronchioles down to terminal bronchioles

### Bronchial Circulation

- **Pressure**: high; part of the systemic circulation
- **Origin**: aorta
- **Vessels**: bronchial arteries and veins, arterioles and venules
- **Function**: feed the tissues of the larger portions of the respiratory tree
- **Rationale**: diffusion is a function of distance; thick bronchial walls cannot self-supply

### Shunts

- **Definition**: a connection between two otherwise separate systems
- **Bronchopulmonary anastomosis**: bronchial blood joins the freshly oxygenated pulmonary stream
- **Proportion**: about two-thirds of bronchial blood supply drains this way
- **Consequence**: blood oxygen content is higher before the anastomosis than after it

### Surface Tension, Laplace and Surfactant

- **Surface tension**: water seeks its lowest volume; molecules stick to each other
- **Boundary molecules**: no bonding partners in the air, so they bond inward, creating the collapsing force
- **Laplace law**: collapsing pressure P = 2T/r
- **Inverse relationship**: smaller radius, molecules closer, higher collapsing pressure
- **Larger alveolus**: molecules farther apart, lower collapsing pressure
- **Surfactant source**: type II pneumocytes, via lamellar bodies
- **Surfactant identity**: dipalmitoyl phosphatidylcholine (DPPC), a phospholipid
- **Mechanism**: inserts between water molecules, breaks up surface tension, works like soap
- **Effect 1**: increased compliance
- **Effect 2**: prevents over-wetting

### Practice Question Logic (Slide 21)

- **Setup**: pulmonary artery occluded, bronchial arteries intact; gas exchange lost, airway walls viable
- **Correct concept**: bronchial circulation from the systemic tree oxygenates conducting airway walls
- **Distractor - flow reversal**: bronchial flow reversal never happens
- **Distractor - pressures swapped**: pulmonary is low-pressure for exchange, bronchial is nutritive
- **Distractor - alveolar supply**: diffusion distance is far too long for thick bronchial walls
- **Distractor - shared origin**: only the pulmonary artery arises from the right ventricle; bronchial arteries arise from the aorta
`
});
